name: 🔥 Deploy to Production

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: fra
  FLY_ORG: forge-42

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://forge42.dev

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
